os:
  - linux

language:
  - python

dist:
  - focal

python:
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libzbar0 python3-opencv

install:
  - pip install tox-travis coveralls

script:
  - tox

after_success:
  - coveralls
